version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo build step

  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test step

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo deploy step && true --secret $MY_SECRET
      - run: echo deploy step, secret $MY_SECRET

  publish-package:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo publish-package step

  perf-testing:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo perf-testing step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
  publish:
    jobs:
      - publish-package:
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore:
                - /.*/
  perf-tests:
    jobs:
      - perf-testing
    triggers:
      - schedule:
          cron: "5 14 * * *"
          filters:
            branches:
              only:
                - master