version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
#      - run:  while true; do sleep 30s && echo "still working at `date '+%I:%M:%S %P'`..."; done
#      - run: node --max-old-space-size=8192 unboundedGrowth.js
#      - run: exit 4
      - run: npm test
      - run: echo Hello Pluralsight
      - run: echo additional build step