version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo build step
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test step
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo deploy step
  test-environment:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo test-environment step
  publish-package:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: echo publish-package step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - sequential_workflow
      - test-environment:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
                - sequential_workflow
  publish:
    jobs:
      - publish-package:
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore:
                - /.*/
